name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set git user
      run: |
        git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
        git config user.name
        git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
        git config user.email
    - name: npm install and test
      run: npm it
